---
Name: silverstripe-colourpicker
---

SilverStripe\Core\Injector\Injector:
  Colour:
    class: MadeHQ\ColourPicker\FieldType\DBColour

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'mademedia/silverstripe-colourpicker:client/dist/thirdparty/jquery-minicolors/jquery.minicolors.min.js'
    - 'mademedia/silverstripe-colourpicker:client/dist/javascript/colourpicker.js'
  extra_requirements_css:
    - 'mademedia/silverstripe-colourpicker:client/dist/thirdparty/jquery-minicolors/jquery.minicolors.css'
    - 'mademedia/silverstripe-colourpicker:client/dist/css/colourpicker.css'
